model:
  name: Qwen/Qwen2-7B-Instruct
  max_length: 512
  device: cuda
redis:
  host: localhost
  port: 6379
  db: 0
  ttl: 3600
database:
  path: ./chatbot.db
api:
  host: 0.0.0.0
  port: 8000
gdpr:
  log_path: ./gdpr_logs/
  anonymize: true
serpapi_key: ""
model_server_url: ""